language: python

python:
  - "3.6"
  - "3.7"

env:
  - TEST_SUITE="adddelete"
  - TEST_SUITE="compartmentedmodel"
  - TEST_SUITE="fixed_recovery"
  - TEST_SUITE="networkdynamics"
  - TEST_SUITE="sir"
  - TEST_SUITE="sirs"
  - TEST_SUITE="sis"
  - TEST_SUITE="seir"
  - TEST_SUITE="stochasticrates"
  - TEST_SUITE="monitor"
  - TEST_SUITE="generators"

install:
    - pip install -r requirements.txt
    - pip install coveralls
  
script:
  - python setup.py install
  - coverage run --include './epydemic/*' -m nose test/test_${TEST_SUITE}.py

after_success:
  - coveralls
