language: python

python:
  - "3.8"

env:
  - TEST_SUITE="adddelete"
  - TEST_SUITE="compartmentedmodel"
  - TEST_SUITE="networkdynamics"
  - TEST_SUITE="sir"
  - TEST_SUITE="sirs"
  - TEST_SUITE="sir_fixedrecovery"
  - TEST_SUITE="sis"
  - TEST_SUITE="sis_fixedrecovery"
  - TEST_SUITE="seir"
  - TEST_SUITE="stochasticrates"
  - TEST_SUITE="monitor"
  - TEST_SUITE="generators"
  - TEST_SUITE="loci"
  - TEST_SUITE="adddelete"
  - TEST_SUITE="percolate"


install:
    - pip install -r requirements.txt
    - pip install coveralls
  
script:
  - python setup.py install
  - coverage run --include './epydemic/*' -m nose test/test_${TEST_SUITE}.py

after_success:
  - coveralls
